services:
  j-server1:
    build:
      context: ./j-server1
      dockerfile: Dockerfile
    ports:
      - ${JSERVER1_PORT}:4003

  j-server2:
    build:
      context: ./j-server2
      dockerfile: Dockerfile
    ports:
      - ${JSERVER2_PORT}:4004

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - JSERVER1_PORT=${JSERVER1_PORT}
      - JSERVER1_NAME=${JSERVER1_NAME}
      - JSERVER2_PORT=${JSERVER2_PORT}
      - JSERVER2_NAME=${JSERVER2_NAME}
    ports:
      - 3003:3003
    volumes:
      - ./server:/app
